---
title: "Data"
output: html_document
---

The dataset used in this analysis is derived from the 2015 Behavioral Risk Factor Surveillance System (BRFSS), a large-scale telephone survey conducted by the Centers for Disease Control and Prevention (CDC). The BRFSS collects health-related information from more than 400,000 Americans annually and is widely recognized as one of the most reliable public health datasets in the United States. The survey collects information on health conditions and social/demographic characteristics through standardized interview procedures. 
In this project, we used a cleaned diabetes health indicators dataset derived from the 2015 BRFSS survey. This dataset contains 70,692 observations and 22 variables, including one target variable and 21 predictive variables. The target variable, Diabetes_binary, classifies individuals as either having diabetes (1) or prediabetes (0). The predictor variables include several health-related indicators such as Body Mass Index (BMI), physical activity, smoking status, blood pressure, cholesterol levels, and stroke history. In addition, the dataset includes demographic variables such as age group, gender, income, and education level. These variables are relevant because public health research has shown strong relationships between lifestyle characteristics, socioeconomic status, and diabetes risk.

More specifically, the dataset was imported into R using the read.csv() function, while also downloading the tidymodels, dplyr, and pROC libraries. Then the target variable, Diabates_binary was converted into a factor variable to support binary classification. Moreover, in order to assess model performance, the data was split into training and testing datasets using the 80/20 train-test split. Additionally, stratified sampling was used in order to maintain the balance of diabetes outcome across both datasets. The functions of head(), summary(), and glimpse() were all used to assess the structure and format of the data prior to modeling. 
Overall, this dataset is applicable for our research question because it has both medical and demographic indicators that are frequently associated with diabetes risk. The large sample size improves the reliability of predictive models and permits patterns to be identified across a diverse population. 

# Limitations:
However, despite this dataset being helpful for predictive models, it is important to acknowledge the limitations. First, BRFSS is a survey that is self-reported, which ultimately can contain bias or inaccurate information. If respondents were to over or underestimate their level of physical exercise, eating behaviors, or smoking status, the data could be skewed inaccurately. Additionally, the dataset is observational instead of being experimental. Hence, the analysis conducted can portray correlations among variables and diabetes risk, however, we can not draw causation. Lastly, the dataset we are using is from 2015, which can be found to be out of date, and inaccurately illustrating health trends and the rate of diabetes, which can influence the significance of our findings to our current society. 

# Data Prep & Cleaning:
Since the dataset was already pre-cleaned, we verified the following details. First, we ensured there were no missing or null values in the dataset. Next, we checked that all data types were correctly formatted. Lastly, we made sure the class balance between diabetic and non-diabetic observations were balanced. Below is a snapshot of the data. 

```{r}

# Import the dataset
data <- read.csv("/Users/brigettemahoney/Desktop/diabetes_binary_5050split_health_indicators_BRFSS2015.csv")

# Check for missing values across all variables
colSums(is.na(data))

# Verify data types
str(data)

# Confirm class balance
table(data$Diabetes_binary)

```

