---
title: "Introduction"
output: html_document
---

Diabetes is a chronic disease in which your body either does not produce enough insulin or does not properly use the insulin it produces. This causes glucose (sugar) to build up in the bloodstream, which leads to potential health complications over time. The three common forms of diabetes are Type 1, Type 2, and gestational diabetes. In Type 1diabetes, the body’s immune system attacks the pancreas and stops insulin production entirely, so people with Type 1 require lifelong daily insulin treatment. Type 2 diabetes, the most common form, develops when the body becomes resistant to insulin or does not produce enough to regulate blood sugar levels efficiently. Unlike Type 1, individuals frequently manage and sometimes reverse Type 2 through healthy eating, weight loss, and physical activity. Gestational diabetes develops during pregnancy and can increase future Type 2 diabetes for both the child and mother. 
According to the Centers for Disease Control and Prevention (CDC), diabetes affects over 40 million Americans (12% of the US population), while an additional 115 million are estimated to have prediabetes. Because Type 2 diabetes often develops over time, individuals can remain undiagnosed until severe health complications occur. Hence, early detection is crucial, as physical activity, healthy nutrition, and medical monitoring can significantly reduce the risk of severe complications. However, for many people, traditional diagnostic testing for diabetes can be expensive, and time-consuming which makes it inaccessible for many Americans. This creates a need for low-cost, efficient, and data-driven approaches that can identify high-risk individuals before severe health complications occur. 
This project aims to explore if machine learning can be used to accurately predict diabetes using health and demographic indicators. More specifically, we investigate the research question: Can we use machine learning to predict diabetes risk using health and demographic indicators? What factors are most predictive of diabetes risk? In using predictive modeling methods in addition to public health data, it strives to identify patterns and trends among individuals characteristics, lifestyles and diabetes outcomes. Additionally, diabetes risk is tied to socioeconomic and demographic factors including income, education, and access to healthcare. This research directly contributes to broader social science discussion of public health inequality and healthcare accessibility for all Americans.
Looking beyond the possible medical implications, this can solve long-term problems, and it also has an economic impact. The American Diabetes Association estimates that the United States spends over $400 billion annually on diabetes-related healthcare costs, placing a burden on government funded healthcare programs and insurance systems. Predictive models could dramatically reduce healthcare costs from both private and governmental insurance standpoint by identifying high-risk individuals to reduce costs through early intervention efforts. Early detection can help people live longer, healthier lives. Having these tools can provide healthcare providers, public health officials, and policy makers with a strategy to improve long-term health outcomes.
To investigate this research question, we used machine learning models, specifically logistic regression and lasso regression, to model diabetes risk. This computational approach makes it possible to estimate the probability that an individual has diabetes based on the health and demographic characteristics by identifying which variables are the strongest predictors of diabetes risk. Lastly, recent academic research has shown that machine learning can be highly effective in predicting diabetes risk using common medical and demographic information. A study conducted using patient data from a Taipei municipal medical center analyzed factors such as plasma glucose levels, BMI, insulin levels, age, blood pressure, and family history to predict diabetes outcomes. Researchers found that advanced machine learning models achieved extremely high predictive accuracy, with some models reaching an Area Under the Curve (AUC) score of 0.991. These findings demonstrate the growing potential for machine learning to support earlier diabetes detection, improve preventative healthcare, and reduce long-term medical complications and healthcare costs.
