<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Methods</title>

<script src="site_libs/header-attrs-2.31/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Diabetes Risk</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Introduction</a>
</li>
<li>
  <a href="Data.html">Data</a>
</li>
<li>
  <a href="Methods.html">Methods</a>
</li>
<li>
  <a href="Results.html">Results</a>
</li>
<li>
  <a href="Conclusion.html">Conclusion</a>
</li>
<li>
  <a href="Contributions.html">Contributions</a>
</li>
<li>
  <a href="https://bmahoney2.shinyapps.io/quiz">Risk Calculator Quiz</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Methods</h1>

</div>


<div id="introduction" class="section level1">
<h1>Introduction:</h1>
<p>To predict diabetes risk, we used three models: logistic regression,
logistic regression with lasso regularization, and random forests.
Importantly, our prediction task is a binary classification problem with
no diabetes = 0 and diabetes/pre-diabetes = 1. Since the CDC prepared
the data by collapsing pre-diabetes and diabetes into one category, we
ran our analysis accordingly using two classifiers.</p>
<p>Logistic regression serves as our baseline model since it predicts
binary outcomes while providing highly interpretable results. To select
for the most predictive features, we also included a lasso penalty term
that selected for only the most predictive features (drove noisy
coefficients to zero). We chose L1 (lasso) regularization over L2
(ridge) regularization to identify only the most predictive features in
our model. Since L1 enacts a sum of absolute value penalty, whereas L2
enacts a sum of squares penalty term, most coefficients get minimized to
zero, thus allowing for only the most predictive features to estimate
model output. This decision to use a Lasso model also made the quiz
section of this project easier to build and interpret. Lastly, as a
robustness check, we included a random forest model to compare the
predictive accuracy of our model across different methods.</p>
<p>First, we imported all necessary libraries for our analysis.</p>
<pre class="r"><code># Import all libraries
library(tidymodels)
library(pROC)
library(dplyr)

# Import the dataset
data &lt;- read.csv(&quot;/Users/brigettemahoney/Desktop/diabetes_binary_5050split_health_indicators_BRFSS2015.csv&quot;)</code></pre>
<p>As discussed in the data preparation section, we checked for null and
missing values. Since this is a government-issued dataset, all entries
were already cleaned and prepared for analysis. Additionally, since the
dataset contains a perfect 50/50 split between patients with and without
diabetes, we did not need to do any data resampling to enforce
representative between classes.</p>
</div>
<div id="logistic-regression" class="section level1">
<h1>Logistic Regression:</h1>
<p>Since this is a supervised learning task, we first defined
“diabetes_binary” as our target variable. We split the data into an
80/20 train test split, since this partition is popular and standard for
most predictive tasks. Then, we trained a logistic regression model that
estimates the probability that a given individual has diabetes based on
a linear combination of the 21 features. Unlike linear regression,
logistic regression restricts outputs between 0-1, which makes the
interpretation of probabilistic risk much more intuitive.</p>
<pre class="r"><code># Source: Course Website (adapted code from linear regression)
# make the target variable (diabetes) binary 
data$Diabetes_binary &lt;- as.factor(data$Diabetes_binary)

# Split data into 80/20 train/split
set.seed(123)
splits &lt;- initial_split(data, prop = 0.8, strata = Diabetes_binary)
train_data &lt;- training(splits)
test_data &lt;- testing(splits)

# Fit the logistic regression on ALL features
log_model &lt;- logistic_reg() %&gt;%
  set_engine(&quot;glm&quot;) %&gt;%
  fit(Diabetes_binary ~ ., data = train_data)

# Predict and compute all probabilities
predictions &lt;- predict(log_model, new_data = test_data)
probs &lt;- predict(log_model, new_data = test_data, type = &quot;prob&quot;)

# Compute the Accuracy 
accuracy &lt;- mean(predictions$.pred_class == test_data$Diabetes_binary)
print(paste(&quot;Accuracy:&quot;, round(accuracy, 3)))</code></pre>
<pre><code>## [1] &quot;Accuracy: 0.748&quot;</code></pre>
<pre class="r"><code># Compute the AUC
roc_curve &lt;- roc(test_data$Diabetes_binary, probs$.pred_1)
print(paste(&quot;AUC:&quot;, round(auc(roc_curve), 3)))</code></pre>
<pre><code>## [1] &quot;AUC: 0.824&quot;</code></pre>
<pre class="r"><code># Print all of the significant coefficients
tidy(log_model) %&gt;% filter(p.value &lt; 0.05) %&gt;% arrange(desc(abs(estimate)))</code></pre>
<pre><code>## # A tibble: 18 × 5
##    term                 estimate std.error statistic   p.value
##    &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1 (Intercept)          -6.88      0.138      -49.8  0        
##  2 CholCheck             1.31      0.0898      14.6  4.22e- 48
##  3 HvyAlcoholConsump    -0.755     0.0547     -13.8  2.21e- 43
##  4 HighBP                0.738     0.0221      33.4  6.19e-244
##  5 HighChol              0.594     0.0211      28.1  3.33e-174
##  6 GenHlth               0.583     0.0128      45.6  0        
##  7 Sex                   0.277     0.0214      12.9  2.55e- 38
##  8 HeartDiseaseorAttack  0.252     0.0317       7.93 2.18e- 15
##  9 Stroke                0.169     0.0456       3.71 2.08e-  4
## 10 Age                   0.150     0.00437     34.5  2.59e-260
## 11 DiffWalk              0.132     0.0288       4.57 4.83e-  6
## 12 BMI                   0.0759    0.00176     43.2  0        
## 13 Veggies              -0.0647    0.0261      -2.48 1.32e-  2
## 14 Income               -0.0598    0.00582    -10.3  8.64e- 25
## 15 Fruits               -0.0447    0.0219      -2.04 4.16e-  2
## 16 Education            -0.0267    0.0114      -2.34 1.95e-  2
## 17 PhysHlth             -0.00821   0.00133     -6.15 7.66e- 10
## 18 MentHlth             -0.00414   0.00143     -2.89 3.87e-  3</code></pre>
<pre class="r"><code># Save the model for quiz later
saveRDS(log_model, &quot;log_model.rds&quot;)</code></pre>
<p>As will be discussed in more detail in the results section, our
logistic regression model produced an Accuracy of 0.743 and an AUC of
0.824. This means that our model correctly classified 74.3% of all
patients in the test set. Additionally, for any randomly chosen person
with diabetes, our model classified them as higher risk than a randomly
chosen person without diabetes 82.4% of the time. 16 out of 21 features
were statistically significant (p&lt;0.05), and a more in-depth analysis
is detailed in the results section.</p>
</div>
<div id="lasso-regression" class="section level1">
<h1>Lasso Regression</h1>
<p>Since 16/21 features were statistically significant, we wanted to
explore if we could achieve similar results using only the most
important features. To do so, we introduced a regularization penalty
term to drive most of the coefficients to zero. Since logistic
regression is a minimizing objective, introducing a penalty term selects
only the most important features. As shown below, we chose a penalty of
0.03 since it produced 9 total coefficients. We believe 9 predictive
features is an optimal number to base our interactive quiz off of, since
it provides a substantial number of features without being exhaustive.
As a result, the 9 most predictive features are: HighBP, GenHlth,
HighChol, Age, BMI, HeartDiseaseorAttack, CholCheck, Income,
HvyAlcoholConsump.</p>
<pre class="r"><code># Run Lasso Regularization 
lasso_model &lt;- logistic_reg(penalty = 0.03, mixture = 1) %&gt;%
  set_engine(&quot;glmnet&quot;) %&gt;%
  fit(Diabetes_binary ~ ., data = train_data)

# run the lasso model
tidy(lasso_model) %&gt;%
# only keep non-zero coefficients
  filter(estimate != 0) %&gt;%
  arrange(desc(abs(estimate)))</code></pre>
<pre><code>## # A tibble: 10 × 3
##    term                 estimate penalty
##    &lt;chr&gt;                   &lt;dbl&gt;   &lt;dbl&gt;
##  1 (Intercept)          -4.28       0.03
##  2 HighBP                0.669      0.03
##  3 GenHlth               0.482      0.03
##  4 HighChol              0.394      0.03
##  5 Age                   0.103      0.03
##  6 HeartDiseaseorAttack  0.0583     0.03
##  7 BMI                   0.0487     0.03
##  8 CholCheck             0.0202     0.03
##  9 HvyAlcoholConsump    -0.0142     0.03
## 10 Income               -0.00881    0.03</code></pre>
<pre class="r"><code># save the model 
saveRDS(lasso_model, &quot;lasso_model.rds&quot;)

# Get all ROC metrics
lasso_probs_roc &lt;- roc(test_data$Diabetes_binary, predict(lasso_model, new_data = test_data, type = &quot;prob&quot;)$.pred_1)
saveRDS(lasso_probs_roc, &quot;lasso_roc.rds&quot;)

# compute and save accuracy metrics
lasso_acc &lt;- mean(predict(lasso_model, test_data)$.pred_class == test_data$Diabetes_binary)
saveRDS(lasso_acc, &quot;lasso_acc.rds&quot;)</code></pre>
</div>
<div id="random-forest-model" class="section level1">
<h1>Random Forest Model</h1>
<p>As a robustness check, we created a random forest model. Random
forests create a sequence of decision trees that can capture non-linear
relationships between features and outcomes. As shown in the code below,
we fit the random forest model using 500 trees and evaluated their
performance using 3-fold cross validation (for timing complexity
reasons). We chose these model parameters to optimize for the model
accuracy / running time tradeoff. Importantly, we added hyperparameters
to strengthen our model. At each split, the model randomly considers
between 2 and 10 features (mtry), and a node must have between 2 and 20
observations before it can split further (min_n). We then analyzed which
combinations of these hyperparameters resulted in the most accurate
model.</p>
<pre class="r"><code># Source: Course Website

# speed up the computation
library(doParallel)
registerDoParallel(parallel::detectCores() - 1)

# create a random forest model
rf_model &lt;- 
  rand_forest(trees = 500, mtry = tune(), min_n = tune()) %&gt;% 
  set_engine(&quot;ranger&quot;) %&gt;% 
  set_mode(&quot;classification&quot;)

# define the random forest workflow
rf_wflow &lt;- 
  workflow() %&gt;% 
  add_formula(Diabetes_binary ~ .) %&gt;% 
  add_model(rf_model)

# set up cross validation
diabetes_folds &lt;- vfold_cv(train_data, v = 3)

keep_pred &lt;- control_resamples(save_pred = TRUE, save_workflow = TRUE)

# Define hyperparameters to adjust the model
rf_grid &lt;- grid_regular(
  mtry(range = c(2, 10)),
  min_n(range = c(2, 20)),
  levels = 2
)

# create a resample object
rf_res &lt;- 
  rf_wflow %&gt;% 
  tune_grid(resamples = diabetes_folds, grid = rf_grid, control = keep_pred)

# examine the metrics across folds
collect_metrics(rf_res)</code></pre>
<pre><code>## # A tibble: 12 × 8
##     mtry min_n .metric     .estimator  mean     n  std_err .config        
##    &lt;int&gt; &lt;int&gt; &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;          
##  1     2     2 accuracy    binary     0.749     3 0.00140  pre0_mod1_post0
##  2     2     2 brier_class binary     0.171     3 0.000756 pre0_mod1_post0
##  3     2     2 roc_auc     binary     0.827     3 0.00211  pre0_mod1_post0
##  4     2    20 accuracy    binary     0.750     3 0.00155  pre0_mod2_post0
##  5     2    20 brier_class binary     0.171     3 0.000765 pre0_mod2_post0
##  6     2    20 roc_auc     binary     0.827     3 0.00215  pre0_mod2_post0
##  7    10     2 accuracy    binary     0.737     3 0.00104  pre0_mod3_post0
##  8    10     2 brier_class binary     0.178     3 0.000809 pre0_mod3_post0
##  9    10     2 roc_auc     binary     0.808     3 0.00199  pre0_mod3_post0
## 10    10    20 accuracy    binary     0.746     3 0.000864 pre0_mod4_post0
## 11    10    20 brier_class binary     0.172     3 0.000840 pre0_mod4_post0
## 12    10    20 roc_auc     binary     0.820     3 0.00204  pre0_mod4_post0</code></pre>
<pre class="r"><code># choose hyperparameters with the best AUC
best_rf &lt;- select_best(rf_res, metric = &quot;roc_auc&quot;)

# choose those hyperparameters for final workflow
final_rf_wflow &lt;- finalize_workflow(rf_wflow, best_rf)
rf_fit &lt;- final_rf_wflow %&gt;% fit(data = train_data)

# fit the final model
final_rf_res &lt;- last_fit(final_rf_wflow, splits)
collect_metrics(final_rf_res)</code></pre>
<pre><code>## # A tibble: 3 × 4
##   .metric     .estimator .estimate .config        
##   &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;          
## 1 accuracy    binary         0.751 pre0_mod0_post0
## 2 roc_auc     binary         0.825 pre0_mod0_post0
## 3 brier_class binary         0.171 pre0_mod0_post0</code></pre>
<pre class="r"><code># AUC
rf_probs &lt;- predict(rf_fit, new_data = test_data, type = &quot;prob&quot;)
rf_roc &lt;- roc(test_data$Diabetes_binary, rf_probs$.pred_1)
print(paste(&quot;Random Forest AUC:&quot;, round(auc(rf_roc), 3)))</code></pre>
<pre><code>## [1] &quot;Random Forest AUC: 0.826&quot;</code></pre>
<pre class="r"><code># accuracy
rf_acc &lt;- mean(predict(rf_fit, test_data)$.pred_class == test_data$Diabetes_binary)
print(paste(&quot;Random Forest Accuracy:&quot;, round(rf_acc, 3)))  # ADD THIS</code></pre>
<pre><code>## [1] &quot;Random Forest Accuracy: 0.75&quot;</code></pre>
<pre class="r"><code># save model
saveRDS(rf_fit, &quot;rf_model.rds&quot;)

# save accuracy values
rf_acc &lt;- mean(predict(rf_fit, test_data)$.pred_class == test_data$Diabetes_binary)</code></pre>
<pre class="r"><code># save all model metrics

saveRDS(probs, &quot;log_probs.rds&quot;)
saveRDS(predict(lasso_model, new_data = test_data, type = &quot;prob&quot;), &quot;lasso_probs.rds&quot;)
saveRDS(rf_probs, &quot;rf_probs.rds&quot;)
saveRDS(roc_curve, &quot;log_roc.rds&quot;)
saveRDS(rf_roc, &quot;rf_roc.rds&quot;)
saveRDS(accuracy, &quot;log_acc.rds&quot;)
saveRDS(rf_acc, &quot;rf_acc.rds&quot;)</code></pre>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
